## Numpy 배열 (Array)
* 순서가 있는, **같은 종류**의 데이터 집합
* 대량의 숫자 데이터를 하나의 변수로 관리
* **리스트보다 작은 메모리 차지, 빠른 데이터 처리 가능**
* 리스트와 달리 **배열의 크기는 고정**! (***생성 후 원소 개수 바꿀 수 없음***)

## 일차원 배열 생성하기

In [1]:
import numpy as np

data1 = [0.1, 5, 4, 12, 0.5] 
a1 = np.array(data1) # 모두 float형으로 변환됨
a1 

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [2]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1, dtype=float) # dtype 옵션 : 명시적으로 자료형 지정
a1

array([0., 1., 2., 3., 4., 5.])

#### 배열 객체의 데이터 타입 확인 : dtype

In [3]:
a1.dtype # a1 배열의 내부 요소들의 자료형

dtype('float64')

In [4]:
type(a1) # a1 객체(변수)의 자료형

numpy.ndarray

#### 범위를 지정해서 배열 생성 : np.arange

In [5]:
a1 = np.arange(0, 10, 2) # [0, 10), step : 2
a1

array([0, 2, 4, 6, 8])

In [6]:
a2 = np.arange(1, 10)
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a3 = np.arange(5)
a3

array([0, 1, 2, 3, 4])

## 다차원 배열 생성하기

In [8]:
b1 = np.arange(12).reshape(4,3) # [0, 12)로 12개 배열 생성 후, 4x3꼴로 변형
b1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## 범위와 데이터 수를 지정해 배열 생성하기
#### np.linspace(start, stop, num)  : [start, stop] 범위의 num개의 요소 배열 생성 (동일 간격)
> ※주의 : arange()와 달리 **np.linspace()는 stop 포함!!**

In [9]:
arr1 = np.linspace(1, 10, 10) # 1~10까지 10개의 수의 배열 생성
arr1

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
arr2 = np.linspace(0, np.pi, 12) # 0~3.14 사이의 12개의 요소 배열 생성
arr2

array([0.        , 0.28559933, 0.57119866, 0.856798  , 1.14239733,
       1.42799666, 1.71359599, 1.99919533, 2.28479466, 2.57039399,
       2.85599332, 3.14159265])

In [11]:
arr2 = np.linspace(0, np.pi, 12).reshape(3, 4)
arr2

array([[0.        , 0.28559933, 0.57119866, 0.856798  ],
       [1.14239733, 1.42799666, 1.71359599, 1.99919533],
       [2.28479466, 2.57039399, 2.85599332, 3.14159265]])

## 난수 배열 생성하기
* **np.random.rand(size)** : [0, 1)사이의 실수 난수 배열 생성
> size 없이 그냥 np.random.rand()만 쓰면, [0, 1)사이의 실수 난수 1개 반환
* **np.random.randint((low), high, size)** : [low, high)사이의 정수 난수 배열 생성
> low 없으면 디폴트 값 0, size 없으면 ~사이의 정수 1개 반환

In [13]:
r_num1 = np.random.rand()
r_num1

0.8903416538331013

In [15]:
r_num2 = np.random.rand(2, 3)
r_num2

array([[0.12637593, 0.87606414, 0.78488788],
       [0.19246419, 0.4432112 , 0.76332177]])

In [16]:
r_num3 = np.random.randint(10, size=(3, 4)) # [0, 10) 사이의 3x4 꼴의 난수 정수 배열
r_num3

array([[4, 2, 8, 7],
       [0, 1, 6, 1],
       [3, 9, 9, 9]])

In [17]:
r_num4 = np.random.randint(1, 30) # [1, 30) 사이 정수 난수 1개
r_num4

1

In [20]:
r_num4 = np.random.randint(30) # [0, 30) 사이 정수 난수 1개
r_num4

11

## 배열 내의 요소 데이터 타입 변환
**astype('f') : 실수형으로 변환**
> 'b' (bool) / 'i' (signed int) / 'u' (unsigned int) / 'S' or 'a' (byte string)

In [23]:
a_str = np.array(['1.567', '0.1234', '5.123', '9', '8'])
print(a_str.dtype) # 유니코드 문자, 배열 항목의 최대 문자('0.1234')개수는 6개! (<U6)
a_num = a_str.astype('f')
print(a_num)
print(a_num.dtype)

<U6
[1.567  0.1234 5.123  9.     8.    ]
float32


In [24]:
test = a_str.astype('float64') # 'f' 대신 이렇게 풀네임으로 적어도 됨
print(test)

[1.567  0.1234 5.123  9.     8.    ]


<hr>

## 스스로 해보기

In [25]:
# a = [1,2,3,4] 리스트를 float 타입 배열 A로 만들기
a = [1,2,3,4]
A = np.array(a, dtype='float')
print(A)

[1. 2. 3. 4.]


In [26]:
# b = [True, False, True] 불타입 리스트를 배열 B로 만들고, 정수형으로 출력
b = [True, False, True]
print(np.array(b).astype('int'))

[1 0 1]


In [28]:
# 리스트 데이터로 원소가 [[1,2,3], [4,5,6]]인 2x3 배열 C만들기
c1 = [[1,2,3], [4,5,6]]
C1 = np.array(c1)
print(C1)

c2 = list(range(1, 7))
C2 = np.array(c2).reshape(2,3)
print(C2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [30]:
# [0,1) 범위의 난수 4 x 5 배열 R과 2~100사이의 정수 중 4x5의 난수 배열 G 생성
R = np.random.rand(4, 5)
G = np.random.randint(2, 100, (4,5))
print(R)
print(G)

[[0.71993283 0.18613592 0.27545401 0.37389935 0.36494634]
 [0.90511021 0.60138836 0.69147985 0.18973838 0.23680467]
 [0.22015405 0.15991809 0.31410827 0.27196024 0.54784338]
 [0.72195882 0.4226259  0.39941336 0.4518313  0.11067935]]
[[57 86 65 25 26]
 [92 73 30  9 84]
 [64 72 47 13 44]
 [98 92 96 58 18]]


In [31]:
# R과 G의 각각의 평균값을 구하고 ,R과 G의 합의 최대값과 최소값을 구하기
print(R.mean())
print(G.mean())
print((R+G).max())
print((R+G).min())

0.40826913333034787
57.45
98.72195882067811
9.189738381179996
